#服务器端口
server:
  port: 8306

dubbo:
  #协议配置端口
  protocol:
    port: 28306

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.prod.url}
    username: ${blade.datasource.prod.username}
    password: ${blade.datasource.prod.password}

